import type { Metadata } from 'next'
import { rubik } from '../components/font';
import './globals.css'
import '../styles/globals.scss';
export const metadata: Metadata = {
  title: 'Transcendance',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={rubik.className}>{children}</body>
    </html>
  )
}
